// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8SHiPo3YzQEpf2K1Z1JiAP
// Component: o1HFECV87K
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantszDahPczOh1KR } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: zDAHPczOh1K_r/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_tester.module.css"; // plasmic-import: 8SHiPo3YzQEpf2K1Z1JiAP/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: o1HFECV87K/css
import landingImg1NJsEc1D9 from "./images/landingImg1.jpeg"; // plasmic-import: nJS-ec1D9/picture

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantszDahPczOh1KR()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        {true ? (
          <p.Stack
            as={"div"}
            data-plasmic-name={"root"}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            hasGap={true}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              sty.root
            )}
          >
            <div className={classNames(projectcss.all, sty.freeBox__hTwh0)}>
              <div className={classNames(projectcss.all, sty.freeBox__uyXnl)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xoIaE)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__fkfmn)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hlGdA
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        <h1
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1__toiPh
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            <h1
                              className={classNames(
                                projectcss.all,
                                projectcss.h1,
                                projectcss.__wab_text,
                                sty.h1__kgGwV
                              )}
                            >
                              {"Event Buddy"}
                            </h1>
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </h1>
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>

                    <p.Stack
                      as={"a"}
                      data-plasmic-name={"loginLinkHomePage"}
                      data-plasmic-override={overrides.loginLinkHomePage}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.loginLinkHomePage
                      )}
                      href={"/login"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jFu2Z
                        )}
                      >
                        {"Login"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"a"}
                      data-plasmic-name={"signUpLinkHomePage"}
                      data-plasmic-override={overrides.signUpLinkHomePage}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.signUpLinkHomePage
                      )}
                      href={"/login-2"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__suvRv
                        )}
                      >
                        {"Sign up"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>

                <div className={classNames(projectcss.all, sty.freeBox__mLWmW)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__iMVa2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3Ribx
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{
                            fontWeight: 700,
                            fontStyle: "italic",
                            textDecorationLine: "underline"
                          }}
                        >
                          {"Find-Book-Enjoy"}
                        </span>
                        <React.Fragment>
                          {
                            "\nWith our all in one, easy to use, event tracker you can find local listings catered toward you!"
                          }
                        </React.Fragment>
                      </React.Fragment>
                    </div>

                    <p.PlasmicImg
                      data-plasmic-name={"img"}
                      data-plasmic-override={overrides.img}
                      alt={""}
                      className={classNames(sty.img)}
                      displayHeight={"585px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"1127px"}
                      loading={"lazy"}
                      src={{
                        src: landingImg1NJsEc1D9,
                        fullWidth: 1200,
                        fullHeight: 630,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__km7Oc)}>
              <div className={classNames(projectcss.all, sty.freeBox__xO6Al)}>
                <div
                  data-plasmic-name={"columns"}
                  data-plasmic-override={overrides.columns}
                  className={classNames(projectcss.all, sty.columns)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__svcfq)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__d7HgM
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{
                            color: "#040404",
                            textDecorationLine: "underline"
                          }}
                        >
                          {"Contact Us"}
                        </span>
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column___2J7Qi)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lvboY
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#040404" }}
                        >
                          {"© 2022 Event Buddy"}
                        </span>
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__wsHx6)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eHsI8
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{
                            color: "#040404",
                            textDecorationLine: "underline"
                          }}
                        >
                          {"Learn More"}
                        </span>
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </p.Stack>
        ) : null}
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "loginLinkHomePage", "signUpLinkHomePage", "img", "columns"],
  loginLinkHomePage: ["loginLinkHomePage"],
  signUpLinkHomePage: ["signUpLinkHomePage"],
  img: ["img"],
  columns: ["columns"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    loginLinkHomePage: makeNodeComponent("loginLinkHomePage"),
    signUpLinkHomePage: makeNodeComponent("signUpLinkHomePage"),
    img: makeNodeComponent("img"),
    columns: makeNodeComponent("columns"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
