// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8SHiPo3YzQEpf2K1Z1JiAP
// Component: Zs2GI_GdgH
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import TextInput from "../../TextInput"; // plasmic-import: 3VlgngjEZhC/component
import { useScreenVariants as useScreenVariantszDahPczOh1KR } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: zDAHPczOh1K_r/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_tester.module.css"; // plasmic-import: 8SHiPo3YzQEpf2K1Z1JiAP/projectcss
import sty from "./PlasmicLoginEb.module.css"; // plasmic-import: Zs2GI_GdgH/css
import landingImg2JpegG5Mpe5Qm from "./images/landingImg2Jpeg.jpeg"; // plasmic-import: g5MPE5qm_/picture
import loginImg2KaTm6W9Xk from "./images/loginImg2.jpeg"; // plasmic-import: KATm6W9Xk/picture

export const PlasmicLoginEb__VariantProps = new Array();

export const PlasmicLoginEb__ArgProps = new Array();

function PlasmicLoginEb__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantszDahPczOh1KR()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"mainSection"}
            data-plasmic-override={overrides.mainSection}
            className={classNames(projectcss.all, sty.mainSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__s950U)}>
              <div className={classNames(projectcss.all, sty.freeBox__dku58)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__uK61M)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__vuKau)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9ObNq
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        <h1
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1__swXVm
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            <h1
                              className={classNames(
                                projectcss.all,
                                projectcss.h1,
                                projectcss.__wab_text,
                                sty.h1__lDq1
                              )}
                            >
                              {"Event Buddy"}
                            </h1>
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </h1>
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>

                    <p.Stack
                      as={"a"}
                      data-plasmic-name={"signUpLink"}
                      data-plasmic-override={overrides.signUpLink}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.signUpLink
                      )}
                      href={"/login-2"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ox3Sy
                        )}
                      >
                        {"Sign up"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </div>
            </div>

            <div
              data-plasmic-name={"pageBanner"}
              data-plasmic-override={overrides.pageBanner}
              className={classNames(projectcss.all, sty.pageBanner)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__oYhtq)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__gHfUm)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__oh4Sx)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__tn8C8)}
                    >
                      <h1
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1__o87Pb
                        )}
                      >
                        {"Welcome Back - Please Log In"}
                      </h1>
                    </p.Stack>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__n4NfQ)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__slWpU)}
                      displayHeight={"401px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: landingImg2JpegG5Mpe5Qm,
                        fullWidth: 275,
                        fullHeight: 183,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </p.Stack>
              </div>
            </div>

            <div
              data-plasmic-name={"mainSection2"}
              data-plasmic-override={overrides.mainSection2}
              className={classNames(projectcss.all, sty.mainSection2)}
            >
              <div className={classNames(projectcss.all, sty.columns__wfgFj)}>
                <div className={classNames(projectcss.all, sty.column__c8Ofp)}>
                  <div
                    data-plasmic-name={"container4"}
                    data-plasmic-override={overrides.container4}
                    className={classNames(projectcss.all, sty.container4)}
                  >
                    <h2
                      data-plasmic-name={"h2"}
                      data-plasmic-override={overrides.h2}
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2
                      )}
                    >
                      {"Login"}
                    </h2>

                    <label
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.label__jfdj
                      )}
                    >
                      {"Email"}
                    </label>

                    <TextInput
                      data-plasmic-name={"loginEmail"}
                      data-plasmic-override={overrides.loginEmail}
                      className={classNames("__wab_instance", sty.loginEmail)}
                      placeholder={" "}
                    />

                    <label
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.label__uEkng
                      )}
                    >
                      {"Password"}
                    </label>

                    <TextInput
                      data-plasmic-name={"loginPassword"}
                      data-plasmic-override={overrides.loginPassword}
                      className={classNames(
                        "__wab_instance",
                        sty.loginPassword
                      )}
                      placeholder={" "}
                    />

                    <a
                      data-plasmic-name={"link"}
                      data-plasmic-override={overrides.link}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link
                      )}
                      href={"https://www.plasmic.app/"}
                    >
                      {"Forgot Password"}
                    </a>

                    <p.Stack
                      as={"a"}
                      data-plasmic-name={"loginConfirmation"}
                      data-plasmic-override={overrides.loginConfirmation}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.loginConfirmation
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ibZ5V
                        )}
                      >
                        {"Confirm"}
                      </div>
                    </p.Stack>
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column__byTlH)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__iBte)}
                    displayHeight={"416px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: loginImg2KaTm6W9Xk,
                      fullWidth: 245,
                      fullHeight: 206,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__fEtEk)}>
              <div className={classNames(projectcss.all, sty.columns__rfr1W)}>
                <div className={classNames(projectcss.all, sty.column__iPrYm)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bqCql
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{
                          color: "#040404",
                          textDecorationLine: "underline"
                        }}
                      >
                        {"Contact Us"}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column__nd6Z6)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jDjAm
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#040404" }}
                      >
                        {"@ 2022 Event Buddy"}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column__lKdvl)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__a4XOi
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{
                          color: "#040404",
                          textDecorationLine: "underline"
                        }}
                      >
                        {"Learn More"}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "mainSection",
    "signUpLink",
    "pageBanner",
    "mainSection2",
    "container4",
    "h2",
    "loginEmail",
    "loginPassword",
    "link",
    "loginConfirmation"
  ],

  mainSection: [
    "mainSection",
    "signUpLink",
    "pageBanner",
    "mainSection2",
    "container4",
    "h2",
    "loginEmail",
    "loginPassword",
    "link",
    "loginConfirmation"
  ],

  signUpLink: ["signUpLink"],
  pageBanner: ["pageBanner"],
  mainSection2: [
    "mainSection2",
    "container4",
    "h2",
    "loginEmail",
    "loginPassword",
    "link",
    "loginConfirmation"
  ],

  container4: [
    "container4",
    "h2",
    "loginEmail",
    "loginPassword",
    "link",
    "loginConfirmation"
  ],

  h2: ["h2"],
  loginEmail: ["loginEmail"],
  loginPassword: ["loginPassword"],
  link: ["link"],
  loginConfirmation: ["loginConfirmation"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLoginEb__ArgProps,
      internalVariantPropNames: PlasmicLoginEb__VariantProps
    });

    return PlasmicLoginEb__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLoginEb";
  } else {
    func.displayName = `PlasmicLoginEb.${nodeName}`;
  }
  return func;
}

export const PlasmicLoginEb = Object.assign(
  // Top-level PlasmicLoginEb renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    mainSection: makeNodeComponent("mainSection"),
    signUpLink: makeNodeComponent("signUpLink"),
    pageBanner: makeNodeComponent("pageBanner"),
    mainSection2: makeNodeComponent("mainSection2"),
    container4: makeNodeComponent("container4"),
    h2: makeNodeComponent("h2"),
    loginEmail: makeNodeComponent("loginEmail"),
    loginPassword: makeNodeComponent("loginPassword"),
    link: makeNodeComponent("link"),
    loginConfirmation: makeNodeComponent("loginConfirmation"),
    // Metadata about props expected for PlasmicLoginEb
    internalVariantProps: PlasmicLoginEb__VariantProps,
    internalArgProps: PlasmicLoginEb__ArgProps
  }
);

export default PlasmicLoginEb;
/* prettier-ignore-end */
